ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'PDP_TRYON_CLICKED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'TRYON_ABANDONED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'CREATIVE_APPROVED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'CREATIVE_REJECTED';
