-- CreateEnum
CREATE TYPE "OutcomeStatus" AS ENUM ('PENDING', 'RESOLVED', 'INCONCLUSIVE', 'ABANDONED');

-- CreateEnum
CREATE TYPE "OutcomeResult" AS ENUM ('IMPROVED', 'NO_CHANGE', 'WORSENED');

-- CreateTable
CREATE TABLE "Outcome" (
    "id" TEXT NOT NULL,
    "shopId" TEXT NOT NULL,
    "recommendationId" TEXT,
    "recommendationType" TEXT NOT NULL,
    "workflowId" TEXT,
    "entityId" TEXT,
    "entityType" TEXT,
    "beforeMetrics" JSONB NOT NULL,
    "afterMetrics" JSONB NOT NULL,
    "delta" JSONB NOT NULL,
    "status" "OutcomeStatus" NOT NULL DEFAULT 'PENDING',
    "resultClass" "OutcomeResult",
    "confidenceScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "resolutionWindowDays" INTEGER NOT NULL DEFAULT 7,
    "resolutionDue" TIMESTAMP(3) NOT NULL,
    "resolvedAt" TIMESTAMP(3),
    "learnedSignal" TEXT NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Outcome_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Outcome_recommendationId_key" ON "Outcome"("recommendationId");

-- CreateIndex
CREATE INDEX "Outcome_shopId_status_idx" ON "Outcome"("shopId", "status");

-- CreateIndex
CREATE INDEX "Outcome_shopId_recommendationType_idx" ON "Outcome"("shopId", "recommendationType");

-- CreateIndex
CREATE INDEX "Outcome_recommendationId_idx" ON "Outcome"("recommendationId");

-- CreateIndex
CREATE INDEX "Outcome_resolutionDue_status_idx" ON "Outcome"("resolutionDue", "status");

-- AddForeignKey
ALTER TABLE "Outcome" ADD CONSTRAINT "Outcome_shopId_fkey" FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Outcome" ADD CONSTRAINT "Outcome_recommendationId_fkey" FOREIGN KEY ("recommendationId") REFERENCES "BrandRecommendation"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AlterEnum: add EventName values added since the clean baseline
-- (all ADD VALUE calls are idempotent when the DB is fresh-created from this migration)
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'WIDGET_EXPERIENCE_SELECTED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'TRYON_RENDER_REQUESTED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'TRYON_RENDER_COMPLETED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'TRYON_RENDER_FAILED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'CHAT_PROFILE_CAPTURED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'CHAT_COMBO_VOTED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'WIDGET_COMBO_VIEWED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'CHAT_IMAGE_MATCH_RUN';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'COMBO_TRYON_REQUESTED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'COMBO_ADD_ALL';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'COMBO_PIECE_SWAPPED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'PRODUCT_DWELL_LONG';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'STYLE_VOTED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'PRODUCT_VIEWED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_ASSISTED_ORDER';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'CART_FROM_MIRA';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'CART_FROM_TRYON';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'CART_FROM_WIDGET_STYLE';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'CHAT_STOCK_CHECKED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'CHAT_SIZE_CHART_VIEWED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'BEAUTY_REPLENISHMENT_TRIGGERED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'BEAUTY_SKIN_PROFILE_CAPTURED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'BEAUTY_SHADE_MATCHED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'BEAUTY_ROUTINE_BUILT';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'BEAUTY_ROUTINE_ADD_ALL';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'BEAUTY_ROUTINE_ADDED_TO_CART';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'BEAUTY_SHADE_GAP_LOGGED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'BEAUTY_INGREDIENT_CONCERN';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'BEAUTY_RESTOCK_ALL';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'PRODUCT_CREATED_VIA_AI';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'CHAT_NEAR_MISS';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'CREATIVE_CLICKED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'CREATIVE_CONVERTED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'OUTCOME_RESOLVED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_OPENED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_PROACTIVE_TRIGGERED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_INTENT_CAPTURED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_PRODUCT_EXPLAINED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_PRODUCT_RECOMMENDED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_OUTFIT_RECOMMENDED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_OUTFIT_ACCEPTED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_OUTFIT_REJECTED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_SIZE_HELP_STARTED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_SIZE_SAVED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_TRYON_OFFERED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_TRYON_STARTED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_TRYON_COMPLETED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_ADD_TO_CART_ASSIST';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_CART_COMPLETED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_HESITATION_DETECTED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_UNMET_DEMAND';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_NEAR_MISS';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_NAVIGATION_FAILED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_SHOPPER_STATE_DETECTED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_BEHAVIORAL_TRIGGER_FIRED';
ALTER TYPE "EventName" ADD VALUE IF NOT EXISTS 'MIRA_BEHAVIORAL_TRIGGER_SUPPRESSED';
